CREATE SEQUENCE DEMO_CUST_SEQ
START WITH 1
INCREMENT BY 1
CACHE 5;

CREATE SEQUENCE DEMO_ACCT_SEQ
START WITH 1
INCREMENT BY 1
CACHE 5;

CREATE TABLE DEMO_CUSTOMER(
CUSTOMER_ID NUMBER(10) NOT NULL,
CUSTOMER_NAME VARCHAR2(50) NOT NULL,
CONSTRAINT DEMO_CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID),
CONSTRAINT DEMO_CUSTOMER_UNIQUE UNIQUE (CUSTOMER_NAME)  
);


CREATE TABLE DEMO_ACCOUNT(
ACCOUNT_NUMER NUMBER(10) NOT NULL,
BALANCE NUMBER(10) NOT NULL,
CUSTOMER_ID NUMBER(10) NOT NULL,
CONSTRAINT DEMO_ACCOUNT_PK PRIMARY KEY (ACCOUNT_NUMER),
CONSTRAINT DEMO_FK_CUSTOMER
  FOREIGN KEY (CUSTOMER_ID)
  REFERENCES DEMO_CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE,
CONSTRAINT DEMO_ACCOUNT_UNIQUE UNIQUE (CUSTOMER_ID)
);