CREATE SEQUENCE CUST_SEQ
START WITH 1
INCREMENT BY 1
CACHE 5;

CREATE SEQUENCE ACCT_SEQ
START WITH 1
INCREMENT BY 1
CACHE 5;

CREATE TABLE CUSTOMER(
CUSTOMER_ID NUMBER(10) NOT NULL,
CUSTOMER_NAME VARCHAR2(50) NOT NULL,
CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID),
CONSTRAINT CUSTOMER_UNIQUE UNIQUE (CUSTOMER_NAME)  
);


CREATE TABLE ACCOUNT(
ACCOUNT_NUMER NUMBER(10) NOT NULL,
BALANCE NUMBER(10) NOT NULL,
CUSTOMER_ID NUMBER(10) NOT NULL,
CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCOUNT_NUMER),
CONSTRAINT FK_CUSTOMER
  FOREIGN KEY (CUSTOMER_ID)
  REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE,
CONSTRAINT ACCOUNT_UNIQUE UNIQUE (CUSTOMER_ID)
);